### ISSUE TITLE
Version 4.0.13 has an import issue

### ISSUE THREAD

**Issue by aadrijnberg** [gregbacchus/validata-koa#14]
When using the validata-koa library in a project, the project compilation fails with the message

node_modules/validata-koa/dist/middleware.types.d.ts:4:14 - error TS2304: Cannot find name 'Request'.

4     request: Request & {
               ~~~~~~~


Found 1 error in node_modules/validata-koa/dist/middleware.types.d.ts:4

error Command failed with exit code 2.
After importing Request from Koa in this file, compilation succeeded.

**Comment by gregbacchus** [comment]
Thanks for the issue and fix :)
